aanish27/employee-profile-manager

- database/seeders/DatabaseSeeder.php
- resources/views/auth/login.blade.php
- resources/views/login.blade.php
- routes/web.php
> make-default-user-account-using-faker-and-seeder

- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
the function is already there , made some changes to the table columns names
> Implemented server side data rendering on datatable

- database/factories/EmployeeFactory.php
- database/seeders/DatabaseSeeder.php
- package-lock.json
- package.json
- resources/js/bootstrap.js
- resources/views/admin.blade.php
Bootstrap 5 added and made some minor changes
> Style integration to datatable

- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
> Deleting a data without reloading page

- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
the issue was on the backend fixed
> datatable-pagination-fix

- app/Http/Controllers/EmployeeController.php
Search is working now please check #20  @Raza9798
> Fix datatable search

- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
> edit update functions implemented

- app/Http/Controllers/CompanyController.php
- app/Models/BankAccount.php
- app/Models/Company.php
- app/Models/Employee.php
- app/Models/Project.php
- database/factories/CompanyFactory.php
- database/factories/EmployeeFactory.php
- database/migrations/2024_09_17_173554_create_companies_table.php
- database/migrations/2024_09_17_175716_add_foreign_key_to_employees.php
- database/migrations/2024_09_17_211338_create_projects_table.php
- database/migrations/2024_09_17_212532_create_table_project_employee.php
- database/migrations/2024_09_17_213443_create_bank_accounts_table.php
- database/migrations/2024_09_17_214231_add_foriegn_key_to_employee.php
- database/seeders/DatabaseSeeder.php
- resources/views/admin.blade.php
- resources/views/company/create.blade.php
- resources/views/company/edit.blade.php
- resources/views/company/index.blade.php
- resources/views/company/show.blade.php
- routes/web.php
implemented a simple CRUD for companies
implemented below relationships
company -> employee  -- 1 - N 
employee ->company -- N - 1
company -> project  -- 1 - N 
project ->company -- N - 1
project -> employee  -- N - N (created a through table)
employee -> BankAccount -- 1 - 1 
@Raza9798
> Relationship practice

- app/Http/Controllers/EmployeeController.php
- app/Models/BankAccount.php
- config/database.php
- resources/views/admin.blade.php
- routes/api.php
- routes/web.php
Fixed both Create and Update to accommodate relationship changes #31 @Raza9798
> Fix update relationship information

- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
Fixed issue  #33 please review @Raza9798
> Fix relationship field on crud

- resources/views/admin.blade.php
- resources/views/company/index.blade.php
confirmation modal for both company and employee implemented #38  @Raza9798
> Delete confirmation integration

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
Controller method fully wrapped inside the try catch block #49 please review @Raza9798
> Response sent from try Block

- app/Http/Controllers/CompanyController.php
- resources/views/company/index.blade.php
fixed #50 please review @Raza9798
> Fix all the edit method and return the specific data

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
- resources/views/company/index.blade.php
Toast notification to render messages implemented #46 @Raza9798 please review
> Toasts notification integration

- resources/views/login.blade.php
> Setup login credentials as default on blade

- app/Models/Company.php
- package-lock.json
- package.json
- resources/css/custom.data-table.css
- resources/js/bootstrap.js
- resources/views/admin.blade.php
- resources/views/company/index.blade.php
- vite.config.js
fixed #60 @Raza9798 Please review
> Fix the datatable layout and component

- resources/css/custom.data-table.css
- resources/views/company/index.blade.php
this commit is from a closed issue...i did changes to only employee view...and in this commit i have copy pasted those changes to company model please merge this...if no issues found @Raza9798 #60
> layout changes for Company

- resources/views/admin.blade.php
#64 Implemented @Raza9798 please review
> Feild label added 

- resources/views/admin.blade.php
- resources/views/components/nav-bar.blade.php
- resources/views/components/sidebar.blade.php
Resolved #77 @Raza9798 Please Review
> svg icon replaced to webfont-icon

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
- resources/views/admin.blade.php
Resolved #79 @Raza9798 Please reveiw
> Datatable ordering fix

- app/Http/Controllers/EmployeeController.php
#81 Resolved @Raza9798 Please review
> Remove multiple model calls and improve search query m emp

- app/Http/Controllers/EmployeeController.php
#80 Resolved @Raza9798 Please Review...
> Remove multiple model calls and improve search query m comp

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
- package-lock.json
- package.json
- resources/css/app.css
- resources/js/bootstrap.js
- resources/views/components/dropdown-filter.blade.php
- resources/views/dashboard/company/index.blade.php
- resources/views/dashboard/employee/index.blade.php
#96 Fixed please reveiw @Raza9798
> Fixed the filer dropdown

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
- app/Models/Employee.php
- package-lock.json
- package.json
- resources/css/app.css
- resources/js/bootstrap.js
- resources/views/components/dropdown-filter.blade.php
- resources/views/dashboard/company/index.blade.php
- resources/views/dashboard/employee/index.blade.php
#93 PR Created please review @Raza9798
> Converting-Controllers-from-Query-builder-to-ORM

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/EmployeeController.php
- app/Models/Employee.php
- database/migrations/2024_09_10_171920_create_employee_table.php
- database/seeders/DatabaseSeeder.php
- resources/views/dashboard/company.blade.php
- resources/views/dashboard/employee.blade.php
#112 fixed please review @Raza9798
> Fixed controller on Delele

- resources/views/dashboard/company.blade.php
- resources/views/dashboard/employee.blade.php
#108 Resolved pleaser review @Raza9798
> inLine Validaition set for Forms

- app/Models/BankAccount.php
- app/Models/Company.php
- app/Models/Employee.php
- app/Models/Project.php
#113 Resolved please review @Raza9798
> Defined primary/foreign keys on modals

- app/Http/Controllers/CompanyController.php
#111 Resolved...it was an unnecessary block of code from the very beginning of the app...therefore i removed it please review
> Company.show Action
